### ISSUE TITLE
support Ecmascript 6 method syntax

### ISSUE THREAD

**Issue by lastobelus** [textmate/javascript.tmbundle#42]
It would be great if the bundle supported [Ecmascript 6 method syntax](http://ariya.ofilabs.com/2013/03/es6-and-method-definitions.html)

I tried  to do it thusly, but don't understand Textmate grammar syntax well enough to make it work:

```
	injections = {
		'source.js - meta.ternary-if.js - string - comment' = {
			patterns = (
				{	name = 'entity.name.function.js';
					match = '(?<!\w)[\p{L}\p{Nl}$_][\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{200C}\x{200D}]*(?=(?:\s*:\s*function\b)|(?:\())';
				},
				{	name = 'entity.name.attribute-name.js';
					match = '(?<!\w)[\p{L}\p{Nl}$_][\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{200C}\x{200D}]*(?=\s*:)';
				},
			);
		};
	};
```

**Comment by whitlockjc** [comment]
There has been a lot of discussion around this.  Long story short is we've talked about this indirectly a number of times because of how different scopes can based on a number of things:

* Environment *(Browser vs. CommonJS vs. Node.js vs. ...)*
* Language Version *(ES5, ES6, ...)*

So what do you do?  Do you end up with a single grammar that handles everything?  That's the approach @infininight suggested.  *(I might remember wrong so feel free to set me straight Michael.)*  Do you end up with a different grammar for the different environments/languages?

Hopefully @infininight will chime in.

**Comment by lastobelus** [comment]
I would be happy with an Ecmascript supplemental bundle with scope `source.js6`. Then in projects or wherever I can set the scope of my .js files to `source.js6`.

**Comment by whitlockjc** [comment]
Agreed.  Scoping is likely to be the answer since it can all be done in one grammar.

**Comment by infininight** [comment]
The grammar has now been updated to support many ECMAScript 6 features, we'll be keeping everything in one grammar. We'll be keeping the main grammar focused on browser work, matching stuff like node.js would be better in an injected or separate grammar.
